---
dist: xenial
language: python
python: "3.7"
os: linux
services:
  - docker
env:
  jobs:
    - DOCKER_BASE_IMAGE=debian:stretch-slim
    - DOCKER_BASE_IMAGE=debian:buster-slim
install:
  - pip install pipenv
  - pipenv sync
script:
  - export DOCKER_BASE_IMAGE=${DOCKER_BASE_IMAGE}
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
