---

- name: PHP | Check if PHP is installed and which version
  command: php --version
  register: php_command_output
  changed_when: false
  failed_when: false

- name: PHP | Set installed fact
  set_fact:
    php_is_installed: "{% if php_command_output.stdout is defined and 'PHP Group' in php_command_output.stdout %}True{% else %}False{% endif %}"

- name: PHP | Set new version fact
  set_fact:
    php_new_version: "{% if php_command_output.stdout is defined and php_version not in php_command_output.stdout %}True{% else %}False{% endif %}"
