---

# TODO check if it has been installed

- name: PHP | Download composer installer
  get_url:
    url: "https://getcomposer.org/installer"
    dest: /usr/src/composer-setup.php

# TODO checksum

- name: PHP | Ensure composer install dir
  file:
    path: "{{ php_composer_install_dir }}"
    state: directory

- name: PHP | Install composer
  command: "php /usr/src/composer-setup.php --filename=composer --install-dir={{ php_composer_install_dir }}"

- name: PHP | Link composer file
  file:
    src: "{{ php_composer_install_dir }}/composer"
    dest: /usr/local/bin/composer
    state: link
