---

- name: PHP | Template php.ini
  template:
    src: "{{ php_ini_configuration_template.src }}"
    dest: "{{ php_ini_configuration_template.dest }}"

- name: PHP | Ensure php executable is symlinked into a standard path.
  file:
    src: "{{ php_install_dir }}/bin/php"
    dest: /usr/bin/php
    state: link
