---

- name: PHP | Template php.ini
  template:
    src: php.ini.j2
    dest: "{{ php_install_dir }}/lib/php.ini"

- name: PHP | Ensure php executable is symlinked into a standard path.
  file:
    src: "{{ php_install_dir }}/bin/php"
    dest: /usr/bin/php
    state: link
