---

- name: PHP | Check
  import_tasks: check.yml
  tags:
    - install

- name: PHP | Install
  import_tasks: install.yml
  tags:
    - install
  when: php_reinstall or not php_is_installed or php_new_version

- name: PHP | Configure PHP
  import_tasks: configure-php.yml
  tags:
    - configure

- name PHP | Configure PCL
  import_tasks: pecl.yml
  tags:
    - configure
  when: php_pear_packages is defined and php_pear_packages|length > 0

- name: PHP | Configure FPM
  import_tasks: configure-fpm.yml
  tags:
    - configure
  when: php_fpm_install

- name: PHP | Service
  import_tasks: service.yml
  tags:
    - service

- name: PHP | Install composer
  import_tasks: composer.yml
  tags:
    - composer
  when: php_composer_install
