---
php_version: 7.4.2

# Files & Paths
php_download_dir: "/usr/src/php_{{ php_version }}"
php_install_dir: "/usr/local/php{{ php_version.split('.') | first }}"
php_unit_file_dir: "/lib/systemd/system/"
php_pid_file: /run/php-fpm.pid


